In [1]:
import numpy as np

In [2]:
ar1=np.array(27)

In [3]:
ar1

array(27)

In [4]:
type(ar1)

numpy.ndarray

In [5]:
ar2=np.array([[2,3,4],[1,0,1]])

In [6]:
ar2

array([[2, 3, 4],
       [1, 0, 1]])

In [7]:
zero_array=np.zeros([6,5])
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
ar3=np.arange(2,9,2)
ar3

array([2, 4, 6, 8])

In [9]:
ar5=np.transpose(ar3)
ar5

array([2, 4, 6, 8])

In [10]:
ar6=np.transpose(ar5)
ar6

array([2, 4, 6, 8])

In [11]:
a1=np.array([1,2])
a2=np.array([4,5])
a1

array([1, 2])

In [16]:
a2

array([4, 5])

In [22]:
concat=np.concatenate((a1,a2))
concat

array([1, 2, 4, 5])

In [23]:
hori=np.vstack((a1,a2))


In [24]:
hori

array([[1, 2],
       [4, 5]])

In [41]:
mat1=np.array([1,2,3])
mat2=np.array([4,5,6])

In [44]:
hori=np.vstack((mat1,mat2))


In [45]:
mat3=np.array  ([[1,2,3,4],[3,4,5,6],[4,5,6,7],[6,7,6,8]])

In [46]:
print(mat3)

[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]
 [6 7 6 8]]


In [49]:
det_of_mat3=np.linalg.det(mat3)

In [51]:
det_of_mat3

-2.2204460492501665e-17

In [52]:
inverse=np.linalg.inv(mat3)

In [53]:
inverse

array([[ 1.35107989e+17, -4.05323966e+17,  2.70215978e+17,
        -5.45000000e+01],
       [-1.80143985e+17,  5.40431955e+17, -3.60287970e+17,
         7.30000000e+01],
       [-4.50359963e+16,  1.35107989e+17, -9.00719925e+16,
         1.75000000e+01],
       [ 9.00719925e+16, -2.70215978e+17,  1.80143985e+17,
        -3.60000000e+01]])

In [55]:
dense=np.array([[1,0,5,0],[2,0,0,5],[5,0,0,0],[0,3,0,6]])

In [56]:
dense

array([[1, 0, 5, 0],
       [2, 0, 0, 5],
       [5, 0, 0, 0],
       [0, 3, 0, 6]])

In [57]:
from scipy .sparse import csr_matrix

In [58]:
sparse=csr_matrix(dense)

In [59]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 7 stored elements in Compressed Sparse Row format>

In [60]:
print(sparse)

  (0, 0)	1
  (0, 2)	5
  (1, 0)	2
  (1, 3)	5
  (2, 0)	5
  (3, 1)	3
  (3, 3)	6
